apiVersion: v1
kind: Pod
metadata:
  name: perfect-one
spec:
  containers:
    - image: mswinarski/perfect-one:7c861a0
      name: perfect-one
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP



