apiVersion: v1
kind: Pod
metadata:
  name: perfect-two
  labels:
    env: prod
spec:
  volumes:
    - name: "perfect-two-data"
      hostPath:
        path: "/Users/mswinarski/Downloads/perfect-two-data"
  containers:
    - image: mswinarski/perfect-two:fd1b663
      name: perfect-two
      volumeMounts:
        - mountPath: "/data"
          name: "perfect-two-data"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          port: 8080
          path: /status/live
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          port: 8080
          path: /status/ready
        initialDelaySeconds: 1
        periodSeconds: 1
      envFrom:
        - configMapRef:
            name: postgres-config







